### ISSUE TITLE
org-fancy-tags?

### ISSUE THREAD

**Issue by rickswe** [harrybournis/org-fancy-priorities#7]
Hello thanks for this awesome package. Have you thought about making something like
org-fancy-tags? Perhaps you can point me in the right direction. I know you can use `org-tag-faces` but I haven't figured out yet how to add emojis yet.

I'm looking to replace my tags with emojis, not sure if something already exists. I'm sure
I could tweak the code some but I read text properties were less taxing than overlays?

```lisp
(defun my/org-fancy-tags ()
  "Description"
  (interactive)
  (save-excursion
    (let (ol)
      (while (re-search-forward ".*:\\(someday\\):" nil t)
	(setq ol (make-overlay (match-beginning 1) (- (match-end 1) 1)))
  ;;(message "...%s" (match-string 2))
	(overlay-put ol 'display (org-fancy-priorities-get-value "☕"))
	(push ol org-fancy-priorities-overlay-list)))))
(my/org-fancy-tags)
```

The org file:
```lisp
* Emacs Package           :org:someday:

Create an emacs package as awesome as org-fancy-priorities.
```

The output:

## Emacs Package    🦄 ☕

Create an emacs package as awesome as org-fancy-priorities.

**Comment by harrybournis** [comment]
@rickalex21 Yes I think you could do that by following the same logic.

 I also used text properties due to performance, specifically the `display` property (check line 133 in org-fancy-priorities.el). The only place where I used overlays was the org-agenda buffer because it is read-only, and Emacs considers updating text properties as "editing" (even though the file is not changed). I think org-tag-faces is just a face, so you can't really change the actual text being displayed, just how it is displayed.

I personally never got into tags, I mean I add them everywhere but then I never use them again, so there's that. I have been meaning to try org-roam for while to see if that works better for me. Good luck with your package, I hope it works out for you.

**Comment by rickswe** [comment]
>specifically the display property

How did you manage to use the display property? It's not allowed in certain sections.
I had to use `char-property-alias-alist` to be able to use it.

>I personally never got into tags

I'm working on something for org capture and now that I think about it, I probably
won't need tags because of inheritance. There's a hack in super agenda which
allows the use org group tags. Not sure if group tags are allowed in regular agenda,
I mostly use super agenda.

>I have been meaning to try org-roam

That's something I've been putting off because I feel like I would open up a can of worms for better or for worse lol.

This is what I came up with, any tips are welcome. I used cl-labels for no reason at all.
The fish tag don't show up when using `:work:fish:dog:home:`, needs some tweaking.

```lisp
(add-to-list 'char-property-alias-alist '(display my-display))
(set-text-properties (point-min) (point-max) nil)
(defvar my/org-super-tags-list '(("work" "🏢")("dog" "🐕")("home" "🏠")("fish" "🐟")) "An alist to match tags with emoji.")
(defun my/org-super-tags ()
  "Set text properties on tags."
(save-excursion
  (let ((emojis my/org-super-tags-list))
    (cl-labels ((search (x) (progn
                        (beginning-of-buffer)
                        (while (re-search-forward
                               (format ":%s:" (nth 0 x)) nil t)(match-beginning 0)
                               (put-text-property (match-beginning 0) (match-end 0) 'my-display (nth 1 x) ))) ))
   (mapcar #'search emojis )))))

```

**Comment by harrybournis** [comment]
You are not seeing "fish" because probably you are also matching the `:` between the tasks. maybe it would be better to match the entire tags string, and then drill down and extract the specific tags. You can check the org mode source code, they probably have a good regex that finds the tags string.
